### ISSUE TITLE
WebSockets requiring secure connections (wss://) on headless clients

### ISSUE THREAD

**Issue by Gawdl3y** [Neos-Metaverse/NeosPublic#2618]
## Describe the bug
Attempting to connect to an insecure WebSocket (ws:// rather than wss://) on headless clients always fails.

## Relevant issues
Appears to be related to a change made for #1755.

## To Reproduce
1. Run a headless client
2. Attempt to connect to an insecure WebSocket from the headless user
3. It will never connect

## Expected behavior
Insecure WebSockets should be usable from headless clients the way they are from the thick game client.

## Log Files
[VM10_-_2021.7.9.1297_-_2021-07-10_16_20_03.log](https://github.com/Neos-Metaverse/NeosPublic/files/6795937/VM10_-_2021.7.9.1297_-_2021-07-10_16_20_03.log)

```
4:22:38 PM.537	Exception running asynchronous task:
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: This instance does not use a secure connection.
   at WebSocketSharp.WebSocket.get_SslConfiguration()
   at FrooxEngine.WebsocketClient.<ConnectTo>d__26.MoveNext() in C:\Sync\Projects\Software\Applications\NeoS\NeosFramework\FrooxEngine\Components\Networking\WebsocketClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.WebsocketClient.<<OnChanges>b__25_0>d.MoveNext() in C:\Sync\Projects\Software\Applications\NeoS\NeosFramework\FrooxEngine\Components\Networking\WebsocketClient.cs:line 78
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: This instance does not use a secure connection.
   at WebSocketSharp.WebSocket.get_SslConfiguration()
   at FrooxEngine.WebsocketClient.<ConnectTo>d__26.MoveNext() in C:\Sync\Projects\Software\Applications\NeoS\NeosFramework\FrooxEngine\Components\Networking\WebsocketClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrooxEngine.WebsocketClient.<<OnChanges>b__25_0>d.MoveNext() in C:\Sync\Projects\Software\Applications\NeoS\NeosFramework\FrooxEngine\Components\Networking\WebsocketClient.cs:line 78<---


   at void FrooxEngine.CoroutineManager.CheckExceptions(Task task) in C:/Sync/Projects/Software/Applications/NeoS/NeosFramework/FrooxEngine/Coroutines/CouroutineManager.cs:line 459
   at bool System.Threading.ThreadPoolWorkQueue.Dispatch()
4:41:37 PM.611	Peer Disconnected: 192.168.2.6:53206, reason: RemoteConnectionClose, socketErrorCode: 0
```

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.7.9.1297
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: Yes, not sure what build

## Additional context
This problem only seems to occur from headless clients, both on Windows and Linux. The game client itself does not seem to be affected, as impulses from actual players to connect to the WebSockets succeed fine. It's only when the headless user tries to connect that it fails (even with the host whitelisted in the headless config).

## Reporters:
- Gawdl3y / Gawdl3y#4269
- Kulza / Kulza#8623
- Epsilion / Epsilion#5028

**Comment by Frooxius** [comment]
Should be fixed in 2021.7.11.1002, thanks for report!
